### ISSUE TITLE
.api functions always use the DS, never pouchdb

### ISSUE THREAD

**Issue by aenario** [cozy/cozy-db#15]
THis is due to the order of require and the fact that we only know to use pouchdb after the configure, so CozyUser & CozyInstance already extends the CozyBackedModel. Easiest way would probably to override them both in the if (pouchdb) as we do for CozyModel.

**Comment by runvnc** [comment]
Ok I am forking and going to try to see if I can figure this out today once I understand the class structure and really understand the problem.

**Comment by runvnc** [comment]
@aenario, @frankrousseau , I think I understand the problem now. Since cozydb.configure redefines CozyModel, I wonder if maybe I should change getCozyInstance and getCozyUser to call cozydb.getModel the first time (and then cache the result), assuming the CozyModel in getModel gets changed by the configure and that the first getModel comes after the configure.  Or maybe I will need to redefine api.CozyInstance and api.CozyUser at the bottom of cozydb.configure.

**Comment by aenario** [comment]
> I should change getCozyInstance and getCozyUser to call cozydb.getModel the first time (and then 
> cache the result)

I think it is the cleaniest way to do it.

**Comment by frankrousseau** [comment]
It sounds good. Can't wait for the fix!
